### ISSUE TITLE
Simplify range comparison

### ISSUE THREAD

**Issue by lkiesow** [virtUOS/cameraConfiguration#15]
Python allows you to compare several values at one, making it unnecessary to split range comparisons.
You can turn something like this:
https://github.com/virtUOS/cameraConfiguration/blob/f4812dea08ee510bf9cd4885812e52fbb923d984/main.py#L24
into something like this:
```py
if 0 <= preset < 101: 
```

**Comment by janmn** [comment]
Changed this and adapted it for Sony cameras. But maybe it is obsolete anyways
